version: "3.8"
services:
  user-db:
    image: postgres
    volumes:
      - user-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${USER_DB_PASSWORD}"
      POSTGRES_USER: "${USER_DB_USER}"
      POSTGRES_DB: "${USER_DB_NAME}"

  user-service:
    image: user-service
    ports:
      - "${USER_SERVICE_PORT}:4000"
    environment:
      DB_HOST: "user-db"
      DB_USER: "${USER_DB_USER}"
      DB_PASSWORD: "${USER_DB_PASSWORD}"
      DB_NAME: "${USER_DB_NAME}"
      JWT_SECRET: "${JWT_SECRET}"
      JWT_EXPIRES_IN: "${JWT_EXPIRES_IN}"
    depends_on:
      - user-db

volumes:
  user-db-data:
