export const CONSTANTS = {
  DB_PORT: 5432,
  API_PORT: 4000,
  EMAIL_REGEX: /^[^\s@]+@[^\s@]+\.com$/,
  MIN_PASSWORD_LENGTH: 6,
  STATUS_CODES: {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    CONFLICT: 409,
    INTERNAL_SERVER_ERROR: 500,
  },
};
